# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM quay.io/jupyterhub/jupyterhub:4.0.2

# Install dockerspawner, nativeauthenticator
# hadolint ignore=DL3013
RUN python3 -m pip install --no-cache-dir \
    dockerspawner jupyterhub-nativeauthenticator==1.0.1

CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
